name:                yesod-test-mocks
version:             1.6.6.1.1
github:              "whittle/yesod-test-mocks"
license:             MIT
author:              "Jason Whittle"
maintainer:          "jason.whittle@gmail.com"
copyright:           "(c) 2019 Jason A. Whittle"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Adds mocks to yesod-test.
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/whittle/yesod-test-mocks#readme>

dependencies:
- base >= 4.7 && < 5
- blaze-builder
- bytestring
- case-insensitive
- conduit
- containers
- cookie
- hspec-core
- html-conduit
- http-types
- HUnit
- network
- pretty-show
- text
- time
- transformers
- wai
- wai-extra
- xml-conduit
- yesod-core
- yesod-test

library:
  source-dirs: src

tests:
  yesod-test-mocks-test:
    main:                main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yesod-test-mocks
    - hspec
    - unliftio
    - yesod-core
    - yesod-form
